language: node_js
node_js:
- "8"
- "10"
before_script:
- CI=false && npm run build:static && CI=true
install:
  npm config set package-lock false
script:
- npm run test
cache:
  directories:
  - node_modules
